# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  # jobs:
  #   pre_build:
  #     - mkdir -p $READTHEDOCS_OUTPUT/html/generated_api
  #     - cp --recursive docs/source/_html/* $READTHEDOCS_OUTPUT/html/generated_api/

# python:
#   install:
#     - requirements: docs/requirements.txt
#     - method: pip
#       path: .  

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
