[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "polyTEM"
authors = [{name = "Christina Cheng", email = "chxcheng@stanford.edu"}]
dynamic = ["version", "description"]
